"""Rename SongLink to Video, and adjust Playlist and Video id fields to accommodate ids generated by YouTube

Revision ID: 857e7a71166e
Revises: f7abbef51e58
Create Date: 2026-01-22 17:23:34.915199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '857e7a71166e'
down_revision: Union[str, Sequence[str], None] = 'f7abbef51e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
    op.create_table('videos',
        sa.Column('id', sa.String(length=32), nullable=False),
        sa.Column('canonical_name_id', sa.Integer(), nullable=False),
        sa.Column('link', sa.String(length=64), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['canonical_name_id'], ['canonical_names.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('canonical_name_id', 'user_id')
    )

    op.drop_index(op.f('song_id'), table_name='song_links')
    op.drop_table('song_links')
    
    op.alter_column('playlists', 'id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('playlists', 'link',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
    


def downgrade() -> None:
    """Downgrade schema."""
    op.alter_column('playlists', 'link',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('playlists', 'id',
               existing_type=sa.String(length=64),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    
    op.create_table('song_links',
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('link', mysql.VARCHAR(length=64), nullable=False),
        sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('song_id', mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['song_id'], ['canonical_names.id'], name=op.f('song_links_ibfk_1'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('song_links_ibfk_2'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )

    op.create_index(op.f('song_id'), 'song_links', ['song_id'], unique=True)
    op.drop_table('videos')
