"""Add video_title and channel_name fields to videos table

Revision ID: f0b9a30c1559
Revises: 857e7a71166e
Create Date: 2026-01-23 15:58:09.138204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0b9a30c1559'
down_revision: Union[str, Sequence[str], None] = '857e7a71166e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('video_title', sa.String(length=128), nullable=False))
    op.add_column('videos', sa.Column('channel_name', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'channel_name')
    op.drop_column('videos', 'video_title')
    # ### end Alembic commands ###
